name: My First Workflow

on:
  push:
   branches:
      - main
   workflow_dispatch: # Allows manual runs via GitHub UI
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
uses: actions/checkout@v3
name: Run a script
        run: echo "Hello, GitHub Actions!"